# $OpenBSD$

COMMENT = tied filehandles for nonblocking io with object callbacks

DISTNAME   = IO-Event-0.813
CATEGORIES = devel

# Perl
PERMIT_PACKAGE_CDROM = Yes

MODULES = cpan

BUILD_DEPENDS = devel/p5-AnyEvent \
                devel/p5-Event

RUN_DEPENDS   = devel/p5-List-MoreUtils

.include <bsd.port.mk>
